import type { ModuleMeta } from "./types";

export const MODULES: ModuleMeta[] = [
  {
    id: "markets-101",
    title: "Markets 101",
    description:
      "Stocks, ETFs, futures, options, exchanges, and how markets work",
    icon: "trending-up-outline",
    order: 1,
    color: "#3B82F6",
    lessonCount: 10,
  },
  {
    id: "probability",
    title: "Probability",
    description: "Expected value, variance, distributions, Bayes theorem",
    icon: "dice-outline",
    order: 2,
    color: "#8B5CF6",
    lessonCount: 10,
  },
  {
    id: "statistics",
    title: "Statistics",
    description:
      "Mean, standard deviation, correlation, regression, hypothesis testing",
    icon: "stats-chart-outline",
    order: 3,
    color: "#06B6D4",
    lessonCount: 10,
  },
  {
    id: "python-for-quants",
    title: "Python for Quants",
    description: "NumPy, Pandas, data analysis with interactive examples",
    icon: "code-slash-outline",
    order: 4,
    color: "#10B981",
    lessonCount: 10,
  },
  {
    id: "backtesting",
    title: "Backtesting",
    description: "Strategy testing, overfitting, walk-forward analysis",
    icon: "flash-outline",
    order: 5,
    color: "#F59E0B",
    lessonCount: 10,
  },
  {
    id: "technical-factors",
    title: "Technical Factors",
    description: "Moving averages, RSI, momentum, volatility, MACD",
    icon: "pulse-outline",
    order: 6,
    color: "#EF4444",
    lessonCount: 10,
  },
  {
    id: "quant-research",
    title: "Quant Research",
    description: "Hypothesis formation, signal generation, alpha evaluation",
    icon: "flask-outline",
    order: 7,
    color: "#EC4899",
    lessonCount: 10,
  },
  {
    id: "market-microstructure",
    title: "Market Microstructure",
    description: "Order books, market making, slippage, latency, HFT",
    icon: "business-outline",
    order: 8,
    color: "#6366F1",
    lessonCount: 10,
  },
  {
    id: "math-for-quants",
    title: "Math for Quants",
    description: "Linear algebra, calculus, optimization, stochastic processes",
    icon: "calculator-outline",
    order: 9,
    color: "#14B8A6",
    lessonCount: 10,
  },
  {
    id: "interview-prep",
    title: "Interview Prep",
    description: "Coding, probability, mental math, brain teasers, systems",
    icon: "briefcase-outline",
    order: 10,
    color: "#F97316",
    lessonCount: 10,
  },
];
